apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tesla-app
  name: tesla-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesla-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tesla-app
    spec:
      containers:
      - image: igbasanmi/tesla-web-app:{{ IMAGE_TAG }}
        name: tesla
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tesla-app
  name: tesla-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tesla-app
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: simple
ingressClassName: nginx
spec:
  rules:
  - host: a9e100485f62d459e8b017fdc48b14dc-1523919885.us-east-2.elb.amazonaws.com
    http:
      paths:
      - backend:
          service:
            name: tesla-svc
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
